// AUTO-GENERATED — DO NOT EDIT
// Generated by code_generator/templates/on_approved_dispatch.ts.jinja2

import type { PrismaClient } from '@/app/generated/prisma/client';

type Tx = Omit<PrismaClient, '$connect' | '$disconnect' | '$on' | '$transaction' | '$use' | '$extends'>;
import { afterApprove as InventoryMovementAfterApprove } from '@/lib/inventory_movement/service_after_approve';
import { afterApprove as InventoryAdjustmentAfterApprove } from '@/lib/inventory_adjustment/service_after_approve';
import { afterApprove as PurchasePerItemAfterApprove } from '@/lib/purchase_per_item/service_after_approve';
import { afterApprove as LeaveRequestAfterApprove } from '@/lib/leave_request/service_after_approve';
import { afterApprove as ReceivingReceiptLineAfterApprove } from '@/lib/receiving_receipt_line/service_after_approve';

/**
 * Dispatch post-approval effects for the approved entity.
 * Called after all terminal approval_requests reach approved status
 * and approvable.approved_at is set (idempotency guaranteed by DB flag).
 */
export async function dispatchOnApproved(
  tx: Tx,
  entityType: string,
  approvableId: string,
  approvedByUserId: string,
): Promise<void> {
  if (entityType === 'inventory_movement') {
    const entity = await tx.inventory_movement.findFirst({ where: { approvable_id: approvableId } });
    if (!entity) return;
    // Custom hook — implement in service_after_approve.ts
    await InventoryMovementAfterApprove(tx, entity.id, approvableId, approvedByUserId);
    return;
  }
  if (entityType === 'inventory_adjustment') {
    const entity = await tx.inventory_adjustment.findFirst({ where: { approvable_id: approvableId } });
    if (!entity) return;
    // Custom hook — implement in service_after_approve.ts
    await InventoryAdjustmentAfterApprove(tx, entity.id, approvableId, approvedByUserId);
    return;
  }
  if (entityType === 'purchase_per_item') {
    const entity = await tx.purchase_per_item.findFirst({ where: { approvable_id: approvableId } });
    if (!entity) return;
    // Custom hook — implement in service_after_approve.ts
    await PurchasePerItemAfterApprove(tx, entity.id, approvableId, approvedByUserId);
    return;
  }
  if (entityType === 'leave_request') {
    const entity = await tx.leave_request.findFirst({ where: { approvable_id: approvableId } });
    if (!entity) return;
    // Standard field update (auto-generated from x-approval.on_approved.set_fields)
    await tx.leave_request.update({
      where: { id: entity.id },
      data: { status: 1 },
    });
    // Custom hook — implement in service_after_approve.ts
    await LeaveRequestAfterApprove(tx, entity.id, approvableId, approvedByUserId);
    return;
  }
  if (entityType === 'receiving_receipt_line') {
    const entity = await tx.receiving_receipt_line.findFirst({ where: { approvable_id: approvableId } });
    if (!entity) return;
    // Custom hook — implement in service_after_approve.ts
    await ReceivingReceiptLineAfterApprove(tx, entity.id, approvableId, approvedByUserId);
    return;
  }
}
