// AUTO-GENERATED — DO NOT EDIT
// Generated by code_generator/templates/on_approved_dispatch.ts.jinja2

import type { PrismaClient } from '@/app/generated/prisma/client';

type Tx = Omit<PrismaClient, '$connect' | '$disconnect' | '$on' | '$transaction' | '$use' | '$extends'>;

/**
 * Dispatch post-approval effects for the approved entity.
 * Called after all terminal approval_requests reach approved status
 * and approvable.approved_at is set (idempotency guaranteed by DB flag).
 */
export async function dispatchOnApproved(
  tx: Tx,
  entityType: string,
  approvableId: string,
  approvedByUserId: string,
): Promise<void> {
  // No approvable entities defined — dispatch is a no-op.
  void tx; void entityType; void approvableId; void approvedByUserId;
}
