FROM postgres:16-alpine
RUN apk add --no-cache git make gcc musl-dev linux-headers postgresql16-dev \
    && git clone --depth 1 --branch v1.2-20240606 \
       https://github.com/pgbigm/pg_bigm.git /tmp/pg_bigm \
    && cd /tmp/pg_bigm \
    && make USE_PGXS=1 \
    && make USE_PGXS=1 install \
    && rm -rf /tmp/pg_bigm \
    && apk del git make gcc musl-dev linux-headers postgresql16-dev
