import type { Metadata } from 'next';
import { getLocale } from 'next-intl/server';
import { siteConfig } from '@/lib/site-config';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import './globals.css';

// Missing `seo` or `seo.noindex` in site-config.ts means noindex — the
// default only flips off when a consumer explicitly sets `noindex: false`.
const noindex = siteConfig.seo?.noindex ?? true;

export const metadata: Metadata = {
  title: siteConfig.title,
  description: 'Application generated by auto-generation code',
  ...(noindex && {
    robots: {
      index: false,
      follow: true,
      googleBot: { index: false, follow: true },
    },
  }),
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body style={{ fontFamily: "'Inconsolata', 'Courier New', monospace" }}>
        <AppRouterCacheProvider>
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
