import { Inconsolata } from 'next/font/google';
import type { Metadata } from 'next';
import { getLocale } from 'next-intl/server';
import { siteConfig } from '@/lib/site-config';
import './globals.css';

const fnt = Inconsolata({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: siteConfig.title,
  description: 'Application generated by auto-generation code',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body className={fnt.className}>{children}</body>
    </html>
  );
}
