// Auto-generated — do not edit manually.
// Source: code_generator/helpers/timezones.py
//
// The stored `Timezone` enum value is an identifier (`asia_tokyo`); this map is the only place its
// IANA spelling is written. Pass `TIMEZONE_IANA_NAME[value]` to Intl.DateTimeFormat or dayjs.tz.
// Display labels live in messages/*.json under the `Timezone` namespace, never here.
export const TIMEZONE_VALUES = [
  'pacific_pago_pago',
  'pacific_honolulu',
  'pacific_marquesas',
  'america_anchorage',
  'america_los_angeles',
  'america_denver',
  'america_chicago',
  'america_mexico_city',
  'america_new_york',
  'america_toronto',
  'america_bogota',
  'america_caracas',
  'america_st_johns',
  'america_sao_paulo',
  'america_nuuk',
  'atlantic_azores',
  'utc',
  'europe_london',
  'europe_madrid',
  'europe_paris',
  'europe_berlin',
  'europe_rome',
  'africa_lagos',
  'africa_cairo',
  'africa_johannesburg',
  'asia_jerusalem',
  'europe_istanbul',
  'europe_moscow',
  'asia_tehran',
  'asia_dubai',
  'asia_kabul',
  'asia_karachi',
  'asia_kolkata',
  'asia_kathmandu',
  'asia_dhaka',
  'asia_yangon',
  'asia_bangkok',
  'asia_jakarta',
  'asia_shanghai',
  'asia_hong_kong',
  'asia_singapore',
  'asia_manila',
  'australia_perth',
  'australia_eucla',
  'asia_seoul',
  'asia_tokyo',
  'australia_adelaide',
  'australia_sydney',
  'australia_lord_howe',
  'pacific_noumea',
  'pacific_auckland',
  'pacific_chatham',
  'pacific_apia',
  'pacific_kiritimati',
] as const;

export type Timezone = (typeof TIMEZONE_VALUES)[number];

export const DEFAULT_TIMEZONE: Timezone = 'utc';

export const TIMEZONE_IANA_NAME: Record<Timezone, string> = {
  pacific_pago_pago: 'Pacific/Pago_Pago',
  pacific_honolulu: 'Pacific/Honolulu',
  pacific_marquesas: 'Pacific/Marquesas',
  america_anchorage: 'America/Anchorage',
  america_los_angeles: 'America/Los_Angeles',
  america_denver: 'America/Denver',
  america_chicago: 'America/Chicago',
  america_mexico_city: 'America/Mexico_City',
  america_new_york: 'America/New_York',
  america_toronto: 'America/Toronto',
  america_bogota: 'America/Bogota',
  america_caracas: 'America/Caracas',
  america_st_johns: 'America/St_Johns',
  america_sao_paulo: 'America/Sao_Paulo',
  america_nuuk: 'America/Nuuk',
  atlantic_azores: 'Atlantic/Azores',
  utc: 'UTC',
  europe_london: 'Europe/London',
  europe_madrid: 'Europe/Madrid',
  europe_paris: 'Europe/Paris',
  europe_berlin: 'Europe/Berlin',
  europe_rome: 'Europe/Rome',
  africa_lagos: 'Africa/Lagos',
  africa_cairo: 'Africa/Cairo',
  africa_johannesburg: 'Africa/Johannesburg',
  asia_jerusalem: 'Asia/Jerusalem',
  europe_istanbul: 'Europe/Istanbul',
  europe_moscow: 'Europe/Moscow',
  asia_tehran: 'Asia/Tehran',
  asia_dubai: 'Asia/Dubai',
  asia_kabul: 'Asia/Kabul',
  asia_karachi: 'Asia/Karachi',
  asia_kolkata: 'Asia/Kolkata',
  asia_kathmandu: 'Asia/Kathmandu',
  asia_dhaka: 'Asia/Dhaka',
  asia_yangon: 'Asia/Yangon',
  asia_bangkok: 'Asia/Bangkok',
  asia_jakarta: 'Asia/Jakarta',
  asia_shanghai: 'Asia/Shanghai',
  asia_hong_kong: 'Asia/Hong_Kong',
  asia_singapore: 'Asia/Singapore',
  asia_manila: 'Asia/Manila',
  australia_perth: 'Australia/Perth',
  australia_eucla: 'Australia/Eucla',
  asia_seoul: 'Asia/Seoul',
  asia_tokyo: 'Asia/Tokyo',
  australia_adelaide: 'Australia/Adelaide',
  australia_sydney: 'Australia/Sydney',
  australia_lord_howe: 'Australia/Lord_Howe',
  pacific_noumea: 'Pacific/Noumea',
  pacific_auckland: 'Pacific/Auckland',
  pacific_chatham: 'Pacific/Chatham',
  pacific_apia: 'Pacific/Apia',
  pacific_kiritimati: 'Pacific/Kiritimati',
};
