/**
 * Site Configuration
 *
 * Edit this file to customize your application.
 * Changes here are reflected throughout the app automatically.
 */

export type NavLink = {
  label: string;
  href: string;
  external?: boolean;
  /** Slug of the NavGroup this link is nested under (see NavGroup below). Absent = top-level (flat) link. */
  group?: string;
  /** Sort position among sibling links/groups within the same group. Only meaningful when `group` is set. */
  order?: number;
};

/**
 * A sidebar navigation group (nested menu). Declared via `x-nav.parent` on an
 * entity (implicit group) or `x-nav-groups` (explicit group-to-group
 * hierarchy) — see docs/knowledge/nested-nav-menu-design.md. Entirely
 * generator-managed; hand edits belong in messages/*.json (label override,
 * see labelKey below), not here.
 */
export type NavGroup = {
  /** Stable identifier — matches NavLink.group and NavGroup.parent references. */
  slug: string;
  /** Key resolved via useTranslations("Nav") in the sidebar, e.g. t(labelKey). */
  labelKey: string;
  /** Sort position among sibling links/groups (ascending). */
  order: number;
  /** Optional icon name — resolved by NavGroupWrapper's ICON_MAP allowlist. */
  icon?: string;
  /** Slug of the parent group, for group-to-group nesting. Absent = top-level group. */
  parent?: string;
};

/**
 * Authentication providers shown on the /login page. Order is preserved in the
 * UI. The list is the *display* gate; each entry has its own runtime gate:
 *
 *   - 'credentials' — the email/password form (always available code-wise; hide
 *     it here to ship an SSO-only deployment).
 *   - 'google'      — only registers server-side when GOOGLE_CLIENT_ID and
 *     GOOGLE_CLIENT_SECRET are both set. If a provider is listed here but its
 *     env vars are missing, clicking its button will fail at the NextAuth
 *     handler — keep the two in sync.
 *
 * MFA / TOTP are not part of the provider list — they layer on top of whichever
 * provider performs the first-factor authentication.
 */
export type AuthProviderId = 'credentials' | 'google';

// ─── App Identity ────────────────────────────────────────────────────────────

export const siteConfig = {
  /** Title shown in the browser tab and the header bar */
  title: "Generated by App Generator",

  /**
   * Authentication providers exposed on the login page. See AuthProviderId
   * above for the runtime gating contract.
   *
   * `allowedDomains` (optional) restricts OAuth sign-in to email addresses
   * whose `@domain` is on the list (case-insensitive). Empty array = allow
   * all. The check only runs for OAuth providers — credentials accounts are
   * created by an admin path, not self-service, so a domain filter there
   * would be defence-in-depth at best.
   */
  auth: {
    providers: ['credentials', 'google'] as AuthProviderId[],
    allowedDomains: [] as string[],
  },

  /** Links listed in the sidebar navigation */
  navLinks: [
    { label: "Home", href: "/", external: false },
    { label: "Audit Log", href: "/audit_log" },
      { label: "User", href: "/user" },
    { label: "Role", href: "/role" },
    { label: "Organization", href: "/organization" },
    { label: "Permission", href: "/permission" },
    { label: "Approval Flow", href: "/approval_flow" },
    { label: "Dashboard", href: "/dashboard" },
  ] satisfies NavLink[],

  /** Sidebar navigation groups (nested menu headers). Empty by default — see NavGroup above. */
  navGroups: [
  ] satisfies NavGroup[],
};

// ─── Theme (Tailwind classes) ─────────────────────────────────────────────────
//
// Change the Tailwind class strings below to restyle the app.
// Full class names must be used (no dynamic concatenation) so Tailwind can
// detect them. See https://tailwindcss.com/docs/customizing-colors for colour
// reference.

export const themeConfig = {
  header: {
    /** Outer <header> bar */
    bar: "bg-blue-900 text-white",
    /** App title text */
    title: "font-bold text-white",
    /** Hamburger / close button */
    menuButton: "hover:bg-white/20 rounded p-1 transition",
    /** Sign-in / sign-out button */
    authButton: "bg-white/20 hover:bg-white/30 text-white rounded px-3 py-1.5 text-sm font-medium transition",
  },
  sidebar: {
    /** Sidebar panel background */
    panel: "bg-gray-100",
    /** Individual nav link */
    link: "text-gray-600 hover:bg-gray-200 block px-4 py-2 no-underline transition",
    /** Overlay backdrop (mobile) */
    backdrop: "bg-black/40",
  },
  content: {
    /** Main content area background */
    background: "bg-orange-50 dark:bg-slate-800",
  },
  footer: {
    bar: "bg-gray-900 text-white",
  },
};
