/**
 * Site Configuration
 *
 * Edit this file to customize your application.
 * Changes here are reflected throughout the app automatically.
 */

export type NavLink = {
  label: string;
  href: string;
  external?: boolean;
};

// ─── App Identity ────────────────────────────────────────────────────────────

export const siteConfig = {
  /** Title shown in the browser tab and the header bar */
  title: "Generated by App Generator",

  /** Links listed in the sidebar navigation */
  navLinks: [
    { label: "Home", href: "/", external: false },
  ] satisfies NavLink[],
};

// ─── Theme (Tailwind classes) ─────────────────────────────────────────────────
//
// Change the Tailwind class strings below to restyle the app.
// Full class names must be used (no dynamic concatenation) so Tailwind can
// detect them. See https://tailwindcss.com/docs/customizing-colors for colour
// reference.

export const themeConfig = {
  header: {
    /** Outer <header> bar */
    bar: "bg-blue-900 text-white",
    /** App title text */
    title: "font-bold text-white",
    /** Hamburger / close button */
    menuButton: "hover:bg-white/20 rounded p-1 transition",
    /** Sign-in / sign-out button */
    authButton: "bg-white/20 hover:bg-white/30 text-white rounded px-3 py-1.5 text-sm font-medium transition",
  },
  sidebar: {
    /** Sidebar panel background */
    panel: "bg-gray-100",
    /** Individual nav link */
    link: "text-gray-700 hover:bg-gray-200 block px-4 py-2 no-underline transition",
    /** Overlay backdrop (mobile) */
    backdrop: "bg-black/40",
  },
  footer: {
    bar: "bg-gray-900 text-white",
  },
};
