/**
 * Site Configuration
 *
 * Edit this file to customize your application.
 * Changes here are reflected throughout the app automatically.
 */

export type NavLink = {
  label: string;
  href: string;
  external?: boolean;
};

/**
 * Authentication providers shown on the /login page. Order is preserved in the
 * UI. The list is the *display* gate; each entry has its own runtime gate:
 *
 *   - 'credentials' — the email/password form (always available code-wise; hide
 *     it here to ship an SSO-only deployment).
 *   - 'google'      — only registers server-side when GOOGLE_CLIENT_ID and
 *     GOOGLE_CLIENT_SECRET are both set. If a provider is listed here but its
 *     env vars are missing, clicking its button will fail at the NextAuth
 *     handler — keep the two in sync.
 *
 * MFA / TOTP are not part of the provider list — they layer on top of whichever
 * provider performs the first-factor authentication.
 */
export type AuthProviderId = 'credentials' | 'google';

// ─── App Identity ────────────────────────────────────────────────────────────

export const siteConfig = {
  /** Title shown in the browser tab and the header bar */
  title: "Generated by App Generator",

  /**
   * Authentication providers exposed on the login page. See AuthProviderId
   * above for the runtime gating contract.
   *
   * `allowedDomains` (optional) restricts OAuth sign-in to email addresses
   * whose `@domain` is on the list (case-insensitive). Empty array = allow
   * all. The check only runs for OAuth providers — credentials accounts are
   * created by an admin path, not self-service, so a domain filter there
   * would be defence-in-depth at best.
   */
  auth: {
    providers: ['credentials', 'google'] as AuthProviderId[],
    allowedDomains: [] as string[],
  },

  /** Links listed in the sidebar navigation */
  navLinks: [
    { label: "Home", href: "/", external: false },
      { label: "Db Table", href: "/db_table" },
    { label: "Xxxxx Xxxxx", href: "/xxxxx_xxxxx" },
    { label: "Parent1", href: "/parent1" },
    { label: "Parent Only", href: "/parent_only" },
    { label: "User Account", href: "/user_account" },
    { label: "Role", href: "/role" },
    { label: "Organization", href: "/organization" },
    { label: "Permission", href: "/permission" },
    { label: "Procedure", href: "/procedure" },
    { label: "Resource", href: "/resource" },
    { label: "Booking", href: "/booking" },
    { label: "Shift Template", href: "/shift_template" },
    { label: "Shift", href: "/shift" },
    { label: "Product", href: "/product" },
    { label: "Inventory", href: "/inventory" },
    { label: "Purchase Order", href: "/purchase_order" },
    { label: "Leave Request", href: "/leave_request" },
    { label: "Approval Flow", href: "/approval_flow" },
    { label: "Dashboard", href: "/dashboard" },
  ] satisfies NavLink[],
};

// ─── Theme (Tailwind classes) ─────────────────────────────────────────────────
//
// Change the Tailwind class strings below to restyle the app.
// Full class names must be used (no dynamic concatenation) so Tailwind can
// detect them. See https://tailwindcss.com/docs/customizing-colors for colour
// reference.

export const themeConfig = {
  header: {
    /** Outer <header> bar */
    bar: "bg-blue-900 text-white",
    /** App title text */
    title: "font-bold text-white",
    /** Hamburger / close button */
    menuButton: "hover:bg-white/20 rounded p-1 transition",
    /** Sign-in / sign-out button */
    authButton: "bg-white/20 hover:bg-white/30 text-white rounded px-3 py-1.5 text-sm font-medium transition",
  },
  sidebar: {
    /** Sidebar panel background */
    panel: "bg-gray-100",
    /** Individual nav link */
    link: "text-gray-700 hover:bg-gray-200 block px-4 py-2 no-underline transition",
    /** Overlay backdrop (mobile) */
    backdrop: "bg-black/40",
  },
  footer: {
    bar: "bg-gray-900 text-white",
  },
};
