// lib/audit_log/virtual_resolvers.ts — stub generated by generate-code (no overwrite)
// VIRTUAL COLUMNS: timestamp
// Implement bulk fetching below. Example (async external API):
//   const results = await externalApi.getInfoBatch(rows.map(r => r.id));
//   return new Map(results.map(r => [String(r.id), { timestamp: r.value }]));
export async function resolveVirtualColumns(
  rows: ReadonlyArray<Record<string, unknown>>
): Promise<Map<string, Record<string, string>>> {
  // Default: return empty values for all rows
  return new Map(
    rows.map(row => [String(row['id'] ?? ''), {}])
  );
}
