import { describe, it, expect, vi } from 'vitest';
import { grantAllPermissions } from './grant-all-permissions';
import { SEED_ENTITIES, SEED_ENTITY_GRANTS } from './generated/seed-entities';

// cmd_1067: grant-all-permissions.ts must never grant Administrator an
// operation x-generate has disabled for that entity (e.g. `create` when
// x-generate.new is false) -- otherwise the generated UI shows an
// affordance (the list page's "+" button, an edit icon) that 404s when
// clicked, because generate.py never wrote the corresponding page/route.
// See docs/knowledge/grant-all-permissions-x-generate-gate.md.
//
// This repo's own dogfood schema already has a live example: 'user' has
// x-generate.new: false and x-generate.delete: false (see
// code_generator/json_schema.yaml), so scripts/generated/seed-entities.ts
// (regenerated by `npm run generate-code`) is real, not a fixture -- these
// tests exercise the actual generated data, not a hand-built stand-in.

type FakeAdminRole = { id: string; creator_id: string };

function makeFakeClient(adminRole: FakeAdminRole | null) {
  const upsertCalls: Array<{ where: unknown; update: unknown; create: unknown }> = [];
  const client = {
    role: {
      findFirst: vi.fn().mockResolvedValue(adminRole),
    },
    permission: {
      upsert: vi.fn().mockImplementation((args: { where: unknown; update: unknown; create: unknown }) => {
        upsertCalls.push(args);
        return Promise.resolve({});
      }),
    },
  };
  return { client, upsertCalls };
}

describe('grantAllPermissions', () => {
  it('throws when the Administrator role does not exist', async () => {
    const { client } = makeFakeClient(null);
    await expect(grantAllPermissions(client as never)).rejects.toThrow(
      /Administrator role not found/,
    );
  });

  it('never grants an operation SEED_ENTITY_GRANTS withholds -- the "user" entity (x-generate.new: false, delete: false) must be upserted with create: false and delete: false', async () => {
    const { client, upsertCalls } = makeFakeClient({ id: 'role-1', creator_id: 'creator-1' });
    await grantAllPermissions(client as never);

    const userCall = upsertCalls.find((c) => (c.where as { name_role_id: { name: string } }).name_role_id.name === 'user');
    expect(userCall).toBeDefined();
    expect(userCall!.update).toEqual(SEED_ENTITY_GRANTS.user);
    expect((userCall!.update as { create: boolean }).create).toBe(false);
    expect((userCall!.update as { delete: boolean }).delete).toBe(false);
    // Sanity: prove this isn't a vacuously-true assertion against an
    // accidentally-all-true fixture -- the real generated data really
    // does withhold something here.
    expect(Object.values(SEED_ENTITY_GRANTS.user)).toContain(false);
  });

  it('upserts every SEED_ENTITIES entity with exactly its own SEED_ENTITY_GRANTS entry, never a blanket {create:true,...}', async () => {
    const { client, upsertCalls } = makeFakeClient({ id: 'role-1', creator_id: 'creator-1' });
    await grantAllPermissions(client as never);

    const grantedNames = upsertCalls.map((c) => (c.where as { name_role_id: { name: string } }).name_role_id.name);
    expect(new Set(grantedNames)).toEqual(new Set(SEED_ENTITIES));

    for (const call of upsertCalls) {
      const name = (call.where as { name_role_id: { name: string } }).name_role_id.name;
      expect(call.update).toEqual(SEED_ENTITY_GRANTS[name]);
      expect(call.create).toMatchObject(SEED_ENTITY_GRANTS[name]);
    }
  });

  it('never upserts audit_log or mfa_recovery_code even if they somehow appeared in SEED_ENTITIES', async () => {
    const { client, upsertCalls } = makeFakeClient({ id: 'role-1', creator_id: 'creator-1' });
    await grantAllPermissions(client as never);

    const grantedNames = upsertCalls.map((c) => (c.where as { name_role_id: { name: string } }).name_role_id.name);
    expect(grantedNames).not.toContain('audit_log');
    expect(grantedNames).not.toContain('mfa_recovery_code');
  });

  it('DRY_RUN mode makes no upsert calls', async () => {
    const original = process.env.DRY_RUN;
    process.env.DRY_RUN = 'true';
    try {
      const { client, upsertCalls } = makeFakeClient({ id: 'role-1', creator_id: 'creator-1' });
      const granted = await grantAllPermissions(client as never);
      expect(upsertCalls).toHaveLength(0);
      expect(granted).toEqual(SEED_ENTITIES.filter((e) => e !== 'audit_log' && e !== 'mfa_recovery_code'));
    } finally {
      process.env.DRY_RUN = original;
    }
  });
});
