/**
 * Development / verification tool — NOT part of the standard seed.
 *
 * Grants the Administrator role CRUD on every independent entity listed in
 * scripts/generated/seed-entities.ts (auto-generated by code-generator from
 * the project schema) — but only the operations that entity's own
 * x-generate config actually generates a page/route for
 * (SEED_ENTITY_GRANTS, see _seed_entity_grant_flags() in
 * code_generator/generators.py). Use this after adding a new entity when
 * you want to exercise it end-to-end without manually opening the
 * Permissions UI first.
 *
 * Deliberately NOT "full" CRUD: granting an operation x-generate has
 * disabled (e.g. `create` when x-generate.new: false) would make the
 * Administrator UI show an affordance — the list page's "+" button, an
 * edit icon — that generate.py never wrote a page/route for, and clicking
 * it 404s. See docs/knowledge/grant-all-permissions-x-generate-gate.md.
 *
 * SAFETY GUARDS:
 *   DRY_RUN=true          Preview changes without writing to the database.
 *   NODE_ENV=production   Refused unless --force is passed.
 *   audit_log / mfa_recovery_code are always excluded — they remain
 *   read-only regardless of what SEED_ENTITIES contains.
 *
 * `scripts/seed-baseline.ts` intentionally does NOT do this: it follows the
 * principle of least privilege, and this script's function is exported
 * (not just a CLI) so it could be wired into seed-baseline.ts with a single
 * import + call if that boundary is ever revisited — see
 * docs/knowledge/seed-baseline-credential-hardening.md.
 */
import path from 'node:path';
import { loadEnvConfig } from '@next/env';
loadEnvConfig(path.resolve(process.cwd()), process.env.NODE_ENV !== 'production');
import { PrismaClient, Prisma } from '@/app/generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { SEED_ENTITIES, SEED_ENTITY_GRANTS, type SeedEntityGrant } from './generated/seed-entities';

// Belt-and-suspenders: SEED_ENTITIES is already structurally guaranteed to
// never contain these (they are Python-injected system_first tables, never
// schema['definitions'] keys — see code_generator/generators.py's
// seed_entities_context()), but audit_log's read-only design is the single
// highest-risk failure mode this script could cause, so it is re-asserted
// explicitly here rather than trusting the upstream guarantee alone.
const ALWAYS_EXCLUDED = new Set(['audit_log', 'mfa_recovery_code']);

const NO_GRANT: SeedEntityGrant = {
  create: false,
  read: false,
  update: false,
  delete: false,
  import: false,
};

// Resolves each entity's per-operation grant. Falls back to NO_GRANT (not
// full access) for an entity missing from SEED_ENTITY_GRANTS — should
// never happen (seed_entities_context() emits one entry per SEED_ENTITIES
// name), but a missing entry must never silently widen into "grant
// everything."
function resolveGrant(entity: string): SeedEntityGrant {
  return SEED_ENTITY_GRANTS[entity] ?? NO_GRANT;
}

export async function grantAllPermissions(
  prisma: PrismaClient,
  tx?: Prisma.TransactionClient,
): Promise<string[]> {
  const client = tx ?? prisma;
  const entitiesToGrant = SEED_ENTITIES.filter((e) => !ALWAYS_EXCLUDED.has(e));

  const adminRole = await client.role.findFirst({ where: { name: 'Administrator' } });
  if (!adminRole) {
    throw new Error('Administrator role not found. Run db:seed-baseline first.');
  }

  const dryRun = process.env.DRY_RUN === 'true';
  if (dryRun) {
    console.log('[DRY RUN] Would grant to Administrator (operation: granted/withheld):');
    entitiesToGrant.forEach((e) => {
      const grant = resolveGrant(e);
      const summary = (Object.keys(grant) as (keyof SeedEntityGrant)[])
        .map((op) => `${op}:${grant[op] ? 'granted' : 'withheld'}`)
        .join(' ');
      console.log(`  ${e} — ${summary}`);
    });
    return entitiesToGrant;
  }

  await Promise.all(
    entitiesToGrant.map((entity) => {
      const grant = resolveGrant(entity);
      return client.permission.upsert({
        where: { name_role_id: { name: entity, role_id: adminRole.id } },
        update: { ...grant },
        create: {
          name: entity,
          role_id: adminRole.id,
          creator_id: adminRole.creator_id,
          updater_id: adminRole.creator_id,
          ...grant,
        },
      });
    }),
  );

  return entitiesToGrant;
}

// CLI entrypoint
if (require.main === module) {
  if (process.env.NODE_ENV === 'production' && !process.argv.includes('--force')) {
    console.error('ERROR: grant-all-permissions refused in production.');
    console.error('Pass --force to override.');
    process.exit(1);
  }

  const connectionString = process.env.DIRECT_URL || process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error('DATABASE_URL is required.');
  }
  const adapter = new PrismaPg({ connectionString });
  const client = new PrismaClient({ adapter });

  grantAllPermissions(client)
    .then((granted) => {
      if (process.env.DRY_RUN !== 'true') {
        console.log(`Granted x-generate-scoped permissions to Administrator for ${granted.length} entities.`);
      }
    })
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
    .finally(async () => {
      await client.$disconnect();
    });
}
