/**
 * Development / verification tool — NOT part of the standard seed.
 *
 * Grants the Administrator role full CRUD on every independent entity
 * listed in scripts/generated/seed-entities.ts (auto-generated by
 * code-generator from the project schema). Use this after adding a new
 * entity when you want to exercise it end-to-end without manually opening
 * the Permissions UI first.
 *
 * SAFETY GUARDS:
 *   DRY_RUN=true          Preview changes without writing to the database.
 *   NODE_ENV=production   Refused unless --force is passed.
 *   audit_log / mfa_recovery_code are always excluded — they remain
 *   read-only regardless of what SEED_ENTITIES contains.
 *
 * `scripts/seed-tenant.ts` intentionally does NOT do this: it follows the
 * principle of least privilege, and this script's function is exported
 * (not just a CLI) so it could be wired into seed-tenant.ts with a single
 * import + call if that boundary is ever revisited — see
 * docs/knowledge/seed-tenant-credential-hardening.md.
 */
import path from 'node:path';
import { loadEnvConfig } from '@next/env';
loadEnvConfig(path.resolve(process.cwd()), process.env.NODE_ENV !== 'production');
import { PrismaClient, Prisma } from '@/app/generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { SEED_ENTITIES } from './generated/seed-entities';

// Belt-and-suspenders: SEED_ENTITIES is already structurally guaranteed to
// never contain these (they are Python-injected system_first tables, never
// schema['definitions'] keys — see code_generator/generators.py's
// seed_entities_context()), but audit_log's read-only design is the single
// highest-risk failure mode this script could cause, so it is re-asserted
// explicitly here rather than trusting the upstream guarantee alone.
const ALWAYS_EXCLUDED = new Set(['audit_log', 'mfa_recovery_code']);

export async function grantAllPermissions(
  prisma: PrismaClient,
  tx?: Prisma.TransactionClient,
): Promise<string[]> {
  const client = tx ?? prisma;
  const entitiesToGrant = SEED_ENTITIES.filter((e) => !ALWAYS_EXCLUDED.has(e));

  const adminRole = await client.role.findFirst({ where: { name: 'Administrator' } });
  if (!adminRole) {
    throw new Error('Administrator role not found. Run db:seed-tenant first.');
  }

  const dryRun = process.env.DRY_RUN === 'true';
  if (dryRun) {
    console.log('[DRY RUN] Would grant full CRUD to Administrator for:');
    entitiesToGrant.forEach((e) => console.log('  ' + e));
    return entitiesToGrant;
  }

  await Promise.all(
    entitiesToGrant.map((entity) =>
      client.permission.upsert({
        where: { name_role_id: { name: entity, role_id: adminRole.id } },
        update: { create: true, read: true, update: true, delete: true, import: true },
        create: {
          name: entity,
          role_id: adminRole.id,
          creator_id: adminRole.creator_id,
          updater_id: adminRole.creator_id,
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
        },
      }),
    ),
  );

  return entitiesToGrant;
}

// CLI entrypoint
if (require.main === module) {
  if (process.env.NODE_ENV === 'production' && !process.argv.includes('--force')) {
    console.error('ERROR: grant-all-permissions refused in production.');
    console.error('Pass --force to override.');
    process.exit(1);
  }

  const connectionString = process.env.DIRECT_URL || process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error('DATABASE_URL is required.');
  }
  const adapter = new PrismaPg({ connectionString });
  const client = new PrismaClient({ adapter });

  grantAllPermissions(client)
    .then((granted) => {
      if (process.env.DRY_RUN !== 'true') {
        console.log(`Granted full CRUD to Administrator for ${granted.length} entities.`);
      }
    })
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
    .finally(async () => {
      await client.$disconnect();
    });
}
